name: shopping_list_ar
description: Arabic shopping list app for Android and Google Play.
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
